"""Render the per-iteration run log required by deliverable 3.

The agent writes `run_log.jsonl` as it goes: one record per iteration holding
the hypothesis, the reasoning behind it, the full code that was run, the
resulting metrics, and any error or repair events.

The deliverable asks for the *code diff* applied each iteration. The run log
stores whole solutions rather than diffs, but every solution is a node in the
search tree and `tree.json` records each node's parent, so the diff is exactly
`parent.code -> node.code` and is recovered here rather than re-derived by hand.

Nothing is invented: every field below is read from the two files, and the
diffs are computed from the code those files already contain. Run:

    python src/engine/make_iteration_log.py

writes deliverables/ITERATION-LOG.md
"""
from __future__ import annotations

import difflib
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = next(p for p in HERE.parents if (p / "deliverables").is_dir())
RUN = ROOT / "deliverables" / "submitted-run"
OUT = ROOT / "deliverables" / "ITERATION-LOG.md"


def load():
    rows = [json.loads(l) for l in (RUN / "run_log.jsonl").read_text().splitlines() if l.strip()]
    nodes = json.loads((RUN / "tree.json").read_text())
    return rows, {n["id"]: n for n in nodes}


def diff_for(node, by_id):
    """Unified diff from the node's parent to the node — the change applied."""
    parent = by_id.get(node.get("parent") or "")
    if parent is None:
        return None
    return "".join(difflib.unified_diff(
        (parent.get("code") or "").splitlines(keepends=True),
        (node.get("code") or "").splitlines(keepends=True),
        fromfile=f"{parent['id']} (primary {parent['primary']:.5f})",
        tofile=f"{node['id']} (primary {node['primary']:.5f})",
    ))


def main():
    rows, by_id = load()
    usage = json.loads((RUN / "usage.json").read_text())
    rule = next((r for r in rows if r.get("event") == "convergence_rule_declared"), {})
    iters = [r for r in rows if isinstance(r.get("iteration"), int) and not r.get("event")]

    # match each scored iteration to its tree node by the summary text both carry
    by_summary = {(n.get("summary") or "").strip(): n for n in by_id.values()}

    out = ["# Per-iteration run log",
           "",
           "KuaiRand-Pure. One section per iteration, covering the four fields the",
           "run-log requirement asks for: the hypothesis and why, the code diff applied,",
           "the resulting metrics, and any error or recovery event.",
           "",
           "Generated by `src/engine/make_iteration_log.py` from",
           "`run_log.jsonl` and `tree.json` in this directory. Diffs are computed from the",
           "code each iteration recorded; every other field is quoted from the log.",
           "",
           f"**Manual interventions during the run: {usage.get('manual_interventions')}.** "
           "The agent chose every hypothesis, wrote every line of the code it ran, and "
           "decided what to keep from validation alone.",
           "",
           "## Stopping rule, declared before the run",
           "",
           "```json",
           json.dumps({k: v for k, v in rule.items() if k != "event"}, indent=2),
           "```",
           "",
           "Recorded as the first line of `run_log.jsonl`, before any iteration ran.",
           "",
           "## Summary",
           "",
           "| # | Outcome | GAUC | nDCG@5 | Primary | Repairs |",
           "|---:|---|---:|---:|---:|---:|"]

    for r in iters:
        it = r["iteration"]
        if r.get("failed"):
            out.append(f"| {it} | crashed ({r.get('failure_class')}) | — | — | — | "
                       f"{r.get('repairs', 0)} |")
            continue
        m = r.get("metrics") or {}
        kept = "**kept**" if r.get("kept") else "rejected"
        out.append(f"| {it} | {kept} | {float(m.get('GAUC', 0)):.5f} | "
                   f"{float(m.get('nDCG@5', 0)):.5f} | {float(m.get('primary', 0)):.5f} | "
                   f"{r.get('repairs', 0)} |")

    out += ["", "---", ""]

    for r in iters:
        it = r["iteration"]
        out.append(f"## Iteration {it}")
        out.append("")
        out.append(f"**Hypothesis.** {r.get('hypothesis', '—')}")
        out.append("")
        if r.get("reasoning"):
            out.append(f"**Why.** {r['reasoning']}")
            out.append("")
        if r.get("prediction"):
            out.append(f"**Prediction stated before running.** {r['prediction']}")
            out.append("")
        if r.get("falsifier"):
            out.append(f"**Falsifier.** {r['falsifier']}")
            out.append("")

        if r.get("failed"):
            out += [f"**Outcome — crashed.** `{r.get('failure_class')}`: "
                    f"`{str(r.get('error'))[:300]}`",
                    "",
                    f"**Recovery.** {r.get('repairs', 0)} repair attempts, each with a shorter "
                    "timeout than the last. The agent could not fix it, so the iteration was "
                    "recorded as a failure and the search continued from the tree. Crashed "
                    "iterations count against the budget but do not advance the convergence "
                    "window.",
                    "", "---", ""]
            continue

        node = by_summary.get((r.get("change_summary") or "").strip())
        out.append("**Code diff applied.**")
        out.append("")
        d = diff_for(node, by_id) if node else None
        if d:
            out += ["```diff", d.rstrip(), "```", ""]
        elif node:
            out += ["First solution on this branch — full code:", "",
                    "```python", (node.get("code") or "").rstrip(), "```", ""]
        else:
            out += ["```python", (r.get("code") or "").rstrip(), "```", ""]

        m = r.get("metrics") or {}
        out += ["**Metrics.**", "",
                f"| GAUC | nDCG@5 | Primary | vs baseline | vs best |",
                f"|---:|---:|---:|---:|---:|",
                f"| {float(m.get('GAUC', 0)):.5f} | {float(m.get('nDCG@5', 0)):.5f} | "
                f"{float(m.get('primary', 0)):.5f} | {m.get('vs_baseline_fm', '—')} | "
                f"{m.get('vs_current_best', '—')} |", ""]

        if r.get("repairs"):
            out += [f"**Recovery.** Crashed on the first attempt and was repaired by the agent "
                    f"in {r['repairs']} attempt(s) within the same iteration, then ran to "
                    f"completion.", ""]

        notes = ((r.get("diagnostics") or {}).get("notes")) or []
        if notes:
            out.append("**What the agent was told afterwards.**")
            out.append("")
            out += [f"- {n}" for n in notes]
            out.append("")

        out.append(f"**Decision.** {'Kept' if r.get('kept') else 'Rejected'}"
                   f" — {'new incumbent' if r.get('kept') else 'incumbent unchanged'}.")
        out += ["", "---", ""]

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(iters)} iterations, "
          f"{OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
